const {firefox}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');const assert=require('assert');
const creds=JSON.parse(fs.readFileSync(process.env.BUFALO_BROWSER_CREDENTIALS || '/tmp/bufalo-production-stage.json','utf8'));
const base=process.env.BUFALO_BROWSER_URL || 'https://localhost:33443';
assert(['localhost','127.0.0.1'].includes(new URL(base).hostname),'Browser CRUD requires loopback staging');
assert(creds.env?.DB_DATABASE?.endsWith('_test'),'Browser CRUD requires an isolated database');const tag=Date.now().toString();const results=[];
(async()=>{
const browser=await firefox.launch({headless:true});const context=await browser.newContext({ignoreHTTPSErrors:true,extraHTTPHeaders:{'CF-Connecting-IP':'198.18.12.1'}});const page=await context.newPage();let current='login';
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await context.route('**/*',route=>{const u=new URL(route.request().url());if(['localhost','127.0.0.1'].includes(u.hostname))return route.continue();return route.abort();});
const go=async path=>{await page.waitForTimeout(350);const r=await page.goto(base+path,{waitUntil:'domcontentloaded'});assert(r.status()===200,`${path}: ${r.status()}`);};
const submit=async selector=>{await page.waitForTimeout(350);await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator(selector).click()]);};
const done=name=>{results.push(name);console.log('PASS '+name);fs.writeFileSync(process.cwd()+'/storage/implementation-backup/admin-browser-progress.json',JSON.stringify({passed:results,errors},null,2));};
try{
await go('/login');await page.locator('[name=email]').fill(creds.email);await page.locator('[name=password]').fill(creds.password);await submit('button[type=submit]');assert(new URL(page.url()).pathname==='/home');done('admin login');
for(const role of ['publicador','chofer']){
current='create '+role;await go('/admin/users/create');const email=`ui-${role}-${tag}@test.invalid`;const name=`UI ${role} ${tag}`;
await page.locator('#name').fill(name);await page.locator('#email').fill(email);await page.locator('#password').fill('Browser!2026Password');await page.locator(`label:has(input[name=role][value=${role}])`).click();assert(await page.locator(`input[name=role][value=${role}]`).isChecked());
for(const [field,value]of Object.entries({city:'La Habana',state:'La Habana',country:'Cuba',radius:'100',phone:'+5355555555',whatsapp:'+5355555555'}))await page.locator('#'+field).fill(value);
await page.locator('#empresa_mode').selectOption('none');
if(role==='chofer'){await page.locator('#chofer_numero_licencia').fill('UI-LIC-'+tag);await page.locator('#chofer_tipo_licencia').fill('A');await page.locator('#chofer_anios_experiencia').fill('3');}
else{await page.locator('#publicador_numero_licencia_broker').fill('UI-BROKER-'+tag);await page.locator('#publicador_anios_experiencia').fill('3');}
await submit('button[type=submit]');assert(new URL(page.url()).pathname==='/admin/users',`create failed ${page.url()}: ${(await page.locator('body').innerText()).slice(0,200)}`);done('create '+role);
current='read/filter '+role;await page.locator('[name=search]').fill(email);await submit('form[action="/admin/users"][method="GET"] button[type=submit]');let row=page.locator('tr').filter({hasText:email});assert(await row.count()===1);const edit=await row.locator('a[title=Editar]').getAttribute('href');done('read/filter '+role);
current='edit '+role;await row.locator('a[title=Editar]').click();await page.waitForLoadState('domcontentloaded');await page.locator('#name').fill(name+' Updated');await submit('button[type=submit]');await go('/admin/users?search='+encodeURIComponent(email));row=page.locator('tr').filter({hasText:email});assert((await row.innerText()).includes('Updated'));done('update '+role);
current='toggle '+role;await submit(`tr:has-text("${email}") button[title="Cambiar estado"]`);await go('/admin/users?search='+encodeURIComponent(email));row=page.locator('tr').filter({hasText:email});assert(await row.locator('.badge.bg-secondary').count()===1,`deactivation row: ${await row.innerText()}`);await submit(`tr:has-text("${email}") button[title="Cambiar estado"]`);await go('/admin/users?search='+encodeURIComponent(email));row=page.locator('tr').filter({hasText:email});assert(await row.locator('.badge.bg-success').count()===1);done('deactivate/reactivate '+role);
current='delete '+role;await submit(`tr:has-text("${email}") button[title="Eliminar"]`);await go('/admin/users?search='+encodeURIComponent(email));assert(await page.locator('tr').filter({hasText:email}).count()===0);done('delete '+role);
}
current='create company';await go('/admin/empresas');await page.getByRole('link',{name:'Crear empresa'}).click();await page.waitForLoadState('domcontentloaded');await page.locator('#tipo').selectOption('carrier');await page.locator('#nombre_legal').fill('UI Company '+tag);await page.locator('#tax_id').fill('UI-TAX-'+tag);await submit('button[type=submit]');assert(!page.url().includes('/create'),'company create failed');done('create company');
current='read company';await go('/admin/empresas?q='+encodeURIComponent('UI Company '+tag));let row=page.locator('tr').filter({hasText:'UI Company '+tag});assert(await row.count()===1);await row.locator('a[title=Ver]').click();await page.waitForLoadState('domcontentloaded');assert((await page.locator('h1').first().innerText()).includes('UI Company'));done('read company');
current='update company';await go('/admin/empresas?q='+encodeURIComponent('UI Company '+tag));row=page.locator('tr').filter({hasText:'UI Company '+tag});await row.locator('a[title=Editar]').click();await page.waitForLoadState('domcontentloaded');await page.locator('#nombre_legal').fill('UI Company '+tag+' Updated');await page.locator('#estado').selectOption('suspendido');await submit('#adminEmpresaEditForm button[type=submit].btn-primary');await go('/admin/empresas?q='+encodeURIComponent('UI Company '+tag));row=page.locator('tr').filter({hasText:'UI Company '+tag});assert((await row.innerText()).includes('Updated'));assert((await row.innerText()).toLowerCase().includes('suspendido'));done('update company/status');
current='delete company';await submit(`tr:has-text("UI Company ${tag}") button[title="Eliminar"]`);await go('/admin/empresas?q='+encodeURIComponent('UI Company '+tag));assert(await page.locator('tr').filter({hasText:'UI Company '+tag}).count()===0);done('delete company');
current='delete company from edit';await go('/empresas/create');await page.locator('#tipo').selectOption('carrier');await page.locator('#nombre_legal').fill('UI Editor Company '+tag);await submit('button[type=submit]');await go('/admin/empresas?q='+encodeURIComponent('UI Editor Company '+tag));row=page.locator('tr').filter({hasText:'UI Editor Company '+tag});await row.locator('a[title=Editar]').click();await page.waitForLoadState('domcontentloaded');assert(await page.locator('button[form="adminEmpresaDeleteForm"]').count()===1);await submit('button[form="adminEmpresaDeleteForm"]');await go('/admin/empresas?q='+encodeURIComponent('UI Editor Company '+tag));assert(await page.locator('tr').filter({hasText:'UI Editor Company '+tag}).count()===0);done('delete company from editor uses independent form');
const {execFileSync}=require('child_process');const database=creds.env;const counts=execFileSync('psql',['-h',database.DB_HOST,'-p',database.DB_PORT,'-U',database.DB_USERNAME,'-d',database.DB_DATABASE,'-At','-c',`SELECT count(*) FROM chofers WHERE numero_licencia='UI-LIC-${tag}'; SELECT count(*) FROM publicadors WHERE numero_licencia_broker='UI-BROKER-${tag}';`],{encoding:'utf8',env:{...process.env,PGPASSWORD:database.DB_PASSWORD}}).trim();assert(counts==='0\n0',`orphan profiles: ${counts}`);done('deleted users leave no orphan role profiles');
await page.setViewportSize({width:390,height:844});await go('/admin/users');assert(await page.locator('a[href="/admin/users/create"]').isVisible());done('mobile admin actions visible');
fs.writeFileSync(process.cwd()+'/storage/implementation-backup/admin-browser-final.json',JSON.stringify({passed:results,errors},null,2));
}catch(e){await page.screenshot({path:process.cwd()+'/storage/implementation-backup/admin-browser-failure.png',fullPage:true});fs.writeFileSync(process.cwd()+'/storage/implementation-backup/admin-browser-failure.json',JSON.stringify({step:current,message:e.message,url:page.url(),passed:results,errors},null,2));throw e;}finally{await browser.close()}
})().catch(e=>{console.error(e.message);process.exit(1)});
