const {firefox}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs');const assert=require('assert');const {execFileSync}=require('child_process');
(async()=>{const browser=await firefox.launch({headless:true});const context=await browser.newContext({ignoreHTTPSErrors:true,extraHTTPHeaders:{'CF-Connecting-IP':`198.18.${Math.floor(Math.random()*240)+10}.${Math.floor(Math.random()*240)+10}`}});await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.BUFALO_BROWSER_URL || 'https://localhost:33443';assert(['localhost','127.0.0.1'].includes(new URL(base).hostname),'Browser registration requires loopback staging');const stage=JSON.parse(fs.readFileSync(process.env.BUFALO_BROWSER_CREDENTIALS || '/tmp/bufalo-production-stage.json','utf8'));assert(stage.env.DB_DATABASE.endsWith('_test'),'Isolated database required');const tag=Date.now().toString();const email=`ui-register-${tag}@test.invalid`;const password='Register!2026Password';const results=[];let current='registration';
try{
await page.goto(base+'/register',{waitUntil:'domcontentloaded'});await page.locator('label:has(input[name=role][value=chofer])').click();await page.locator('#preferred_equipment_types').waitFor({state:'visible'});
assert(await page.locator('#preferred_equipment_types option').count()===9);assert(await page.locator('#preferred_cargo_types option').count()===6);results.push('canonical catalogs selectable');
for(const [field,value]of Object.entries({name:'UI Registration '+tag,email,password,city:'La Habana',state:'La Habana',country:'Cuba',radius:'100',phone:'+5355555555',whatsapp:'+5355555555',chofer_numero_licencia:'UI-REG-'+tag,chofer_tipo_licencia:'A',chofer_anios_experiencia:'3'}))await page.locator('#'+field).fill(value);
await page.locator('#preferred_equipment_types').selectOption(['dry_van','reefer']);await page.locator('#preferred_cargo_types').selectOption(['FTL','LTL']);await page.locator('#chofer_tipos_equipo_permitidos').selectOption(['flatbed','reefer']);
await page.locator('#name').fill('x');await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator('button[type=submit]').click()]);await page.locator('#preferred_equipment_types').waitFor({state:'visible'});assert.deepStrictEqual(await page.locator('#preferred_equipment_types').evaluate(e=>Array.from(e.selectedOptions,o=>o.value)),['dry_van','reefer']);results.push('selection preserved on validation');
await page.locator('#name').fill('UI Registration '+tag);await page.locator('#password').fill(password);await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator('button[type=submit]').click()]);assert((await page.locator('h1').innerText()).includes('Confirma tu correo'));await page.getByRole('button',{name:'Reenviar confirmación'}).waitFor({state:'visible'});results.push('registration waits for email');
// Read only the locally captured message for this synthetic address; no real
// SMTP is involved and activation is completed through the browser form.
current='mail confirmation';const folder=process.env.BUFALO_CAPTURE_DIR || '/tmp/bufalo-modal-smtp';const file=fs.readdirSync(folder).filter(x=>x.endsWith('.eml')).find(x=>fs.readFileSync(folder+'/'+x,'utf8').includes(email));assert(file,'captured confirmation missing');const message=fs.readFileSync(folder+'/'+file,'utf8').replace(/=\r?\n/g,'').replace(/=3D/g,'=');const match=message.match(/https:\/\/localhost:33443\/register\/confirm\?token=([A-Za-z0-9_-]+)/);assert(match,'confirmation token missing');
await page.goto(base+'/register/confirm?token='+match[1],{waitUntil:'domcontentloaded'});const confirmationRequest=page.waitForRequest(r=>r.method()==='POST' && new URL(r.url()).pathname==='/register/confirm');await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator('button[type=submit]').click()]);assert((await page.locator('body').innerText()).includes('Correo confirmado'));const confirmationHeaders=await (await confirmationRequest).allHeaders();assert(!String(confirmationHeaders.referer||'').includes('token='));results.push('email confirmation through UI without token in Referer');
await page.locator('[name=email]').fill(email);await page.locator('[name=password]').fill(password);await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator('button[type=submit]').click()]);assert(new URL(page.url()).pathname==='/home');results.push('new driver login');
await page.goto(base+'/profile',{waitUntil:'domcontentloaded'});assert((await page.locator('body').innerText()).includes('UI Registration'));results.push('new profile accessible');
// Verify persisted preferences without modifying the account through SQL.
const sql=`SELECT preferred_equipment_types,preferred_cargo_types FROM users WHERE email='${email}'; SELECT tipos_equipo_permitidos FROM chofers WHERE user_id=(SELECT id FROM users WHERE email='${email}');`;
const stored=execFileSync('psql',['-h',stage.env.DB_HOST,'-p',stage.env.DB_PORT,'-U',stage.env.DB_USERNAME,'-d',stage.env.DB_DATABASE,'-At','-c',sql],{encoding:'utf8',env:{...process.env,PGPASSWORD:stage.env.DB_PASSWORD}});assert(stored.includes('dry_van,reefer|FTL,LTL'));assert(stored.includes('flatbed,reefer'));results.push('preferences persisted after confirmation');
await page.setViewportSize({width:390,height:844});await page.goto(base+'/logout',{waitUntil:'domcontentloaded'});await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.locator('button[type=submit]').click()]);await page.goto(base+'/register',{waitUntil:'domcontentloaded'});await page.locator('label:has(input[name=role][value=chofer])').click();await page.locator('#preferred_equipment_types').waitFor({state:'visible'});results.push('mobile selectors visible');
fs.writeFileSync(process.cwd()+'/storage/implementation-backup/register-browser-final.json',JSON.stringify({passed:results,errors},null,2));console.log(JSON.stringify({passed:results,errors}));
}catch(e){await page.screenshot({path:process.cwd()+'/storage/implementation-backup/register-browser-failure.png',fullPage:true});console.error(current+': '+e.message);throw e}finally{await browser.close()}})().catch(e=>process.exit(1));
